### ISSUE TITLE
where is requirements.txt

### ISSUE THREAD

**Issue by emptykk** [sterzhang/image-textualization#3]
1. Clone Repositories and Related Packages
1.1 image-textualization
git clone https://github.com/sterzhang/image-textualization.git
cd image-textualization
conda create --name image-textualization python=3.8 -y
conda activate image-textualization
pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
**pip install -r requirements.txt**

**Comment by sterzhang** [comment]
> 1. Clone Repositories and Related Packages
>    1.1 image-textualization
>    git clone https://github.com/sterzhang/image-textualization.git
>    cd image-textualization
>    conda create --name image-textualization python=3.8 -y
>    conda activate image-textualization
>    pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
>    **pip install -r requirements.txt**

Hi, thank you for your interest! Actually you can just skip this part, we just use the requirements of the vision experts we use (Groundingdino, detectron2, GRiT, SAM), you can install the corresponding packages   of their repos. For the recaptioning phrase, you can just install packages according to LLama3.
