### ISSUE TITLE
Question about dataset source

### ISSUE THREAD

**Issue by lockon-n** [sterzhang/image-textualization#5]
Thanks for this nice work first! I have a question about the source of your released 170k dataset. Is the dataset based on GPT4V or LLaVA? I did not find details about it in your paper. Thanks in advance!

**Comment by sterzhang** [comment]
Thanks for your interest! As you can see in our huggingface, we utilize four MLLMs to generate our first stage Reference Description, to be specific, we use LLaVA, GPT4V, ShareGPT4v, and InternVL respectively.  For example, "image-textualization-vg-internvl.jsonl" shows the results of refined description based on InternVL-generated Reference Description on the VG dataset.
<img width="1384" alt="image" src="https://github.com/user-attachments/assets/05447f57-f914-42e2-9d1b-07b045f4446d">

**Comment by lockon-n** [comment]
Thanks for the quick response, really helpful!
