### ISSUE TITLE
extr_fr_image behave badly on black-and-white pictures

### ISSUE THREAD

**Issue by tian969** [sterzhang/image-textualization#7]
I found that some images were missing in `fg_anno.jsonl`. After downloading these images, I noticed they all had a common characteristic: they were black and white photos. I specifically ran `extract/extract_fr_img.py` on these photos, and the recognition errors were numerous. Even after increasing the threshold, some of them did not display at all.

eg:
![image](https://github.com/user-attachments/assets/535ae967-34b5-47ed-a1e2-420e2ee01989)

00554/005543541.jpg
![005543541](https://github.com/user-attachments/assets/16c69e4c-88ad-463c-a5a0-dbb2553a3286)

00241/002415765.jpg
![002415765](https://github.com/user-attachments/assets/cb8cbc93-2141-47fe-b0f9-c3a31bea5bc9)

**Comment by sterzhang** [comment]
The vision expert (GRiT) for extracting objects from image just supports common objects (as black and white drawings are not in its training set). 
Moreover, MLLMs already experts in understanding this type of drawings, and the aim of the introduce of smaller vision experts is to mitigate drawbacks of MLLMs.
Therefore, there seems no need to use our IT framework in this settings.
